<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DenunciasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('denuncias')->insert([
            [
                'user_id' => '1',
                'titulo' => 'calle de barrio cupesi en mal estado',
                'descripcion' => 'calle con baches enormes y profundos que arruinan los automoviles',
                'fecha' => Carbon::now(),
                'hora' => Carbon::now(),
                'hash' => 'c4ca4238a0b923820dcc509a6f75849b',
                'latitud' => '-17.78071410558826',
                'longitud' => '-63.16718255919403',
                'tipo_denuncia' => '4',
            ],
            [
                'user_id' => '1',
                'titulo' => 'calle de barrio hombres nuevos en mal estado',
                'descripcion' => 'calle con baches profundos que arruinan el paso de los automoviles',
                'fecha' => Carbon::now(),
                'hora' => Carbon::now(),
                'hash' => 'c4ca4238a0b923820dcc509a6f75849y',
                'latitud' => '-17.767097400305005',
                'longitud' => '-63.178601191885654',
                'tipo_denuncia' => '4',
            ],
            [
                'user_id' => '1',
                'titulo' => 'calle de barrio cumavi en mal estado',
                'descripcion' => 'calle con baches medianos y profundos',
                'fecha' => Carbon::now(),
                'hora' => Carbon::now(),
                'hash' => 'c81e728d9d4c2f636f067f89cc14862c',
                'latitud' => '-17.786146505331555',
                'longitud' => '-63.167728782362964',
                'tipo_denuncia' => '4',
            ],
            [
                'user_id' => '2',
                'titulo' => 'plazuela el mechero sin iluminacion',
                'descripcion' => 'la plazuela esta a oscuras',
                'fecha' => Carbon::now(),
                'hora' => Carbon::now(),
                'hash' => 'eccbc87e4b5ce2fe28308fd9f2a7baf3',
                'latitud' => '-17.77510815821113',
                'longitud' => '-63.188181805466655',
                'tipo_denuncia' => '5',
            ],
            [
                'user_id' => '1',
                'titulo' => 'plazuela el mechero 2 sin iluminacion',
                'descripcion' => 'la plazuela esta a oscuras',
                'fecha' => Carbon::now(),
                'hora' => Carbon::now(),
                'hash' => 'eccbc87e4b5ce2fe28308fd9f2a7baf8',
                'latitud' => '-17.80762097039071',
                'longitud' => '-63.176238782509806',
                'tipo_denuncia' => '5',
            ],
            [
                'user_id' => '2',
                'titulo' => 'parque los mangalitos sin luz',
                'descripcion' => 'el parquesito esta sin iluminarias y es peligroso de noche debido a esto',
                'fecha' => Carbon::now(),
                'hora' => Carbon::now(),
                'hash' => 'e4da3b7fbbce2345d7772b0674a318d5',
                'latitud' => '-17.788053585208385',
                'longitud' => '-63.18162712743937',
                'tipo_denuncia' => '5',
            ],
            [
                'user_id' => '3',
                'titulo' => 'calle montenegro inundada',
                'descripcion' => 'la calle esta totalmente inundada de agua, imposible transitar',
                'fecha' => Carbon::now(),
                'hora' => Carbon::now(),
                'hash' => '1679091c5a880faf6fb5e6087eb1b2dc',
                'latitud' => '-17.786724410475042',
                'longitud' => '-63.18029191524861',
                'tipo_denuncia' => '3',
            ],
            [
                'user_id' => '1',
                'titulo' => 'calle heroes del chaco inundada',
                'descripcion' => 'la calle esta totalmente inundada de agua, imposible transitar',
                'fecha' => Carbon::now(),
                'hora' => Carbon::now(),
                'hash' => '1679091c5a880faf6fb5e6087eb1b2d7',
                'latitud' => '-17.766753738334053',
                'longitud' => '-63.18589083859314',
                'tipo_denuncia' => '3',
            ],
            [
                'user_id' => '3',
                'titulo' => 'calle bibosi inundada',
                'descripcion' => 'la calle esta totalmente inundada de agua, imposible transitar a pie ni en vehiculo',
                'fecha' => Carbon::now(),
                'hora' => Carbon::now(),
                'hash' => '1679091c5a880faf6fb5e6087eb1b2dc',
                'latitud' => '-17.789729487075906',
                'longitud' => '-63.1836906371887',
                'tipo_denuncia' => '3',
            ],
            [
                'user_id' => '1',
                'titulo' => 'barrio esperanza 2 con basura amontonada',
                'descripcion' => 'la calles del barrio estan amontonadas de basura',
                'fecha' => Carbon::now(),
                'hora' => Carbon::now(),
                'hash' => '8f14e45fceea167a5a36dedd4bea2543',
                'latitud' => '-17.78897822266649',
                'longitud' => '-63.186482444496605',
                'tipo_denuncia' => '2',
            ],
            [
                'user_id' => '2',
                'titulo' => 'barrio urupau con basura amontonada',
                'descripcion' => 'la calles del barrio estan amontonadas de basura y genera malos olores',
                'fecha' => Carbon::now(),
                'hora' => Carbon::now(),
                'hash' => '8f14e45fceea167a5a36dedd4bea2541',
                'latitud' => '-17.811508133521716',
                'longitud' => '-63.179300896541086',
                'tipo_denuncia' => '2',
            ],
            [
                'user_id' => '2',
                'titulo' => 'barrio la colorada con basura acumulada',
                'descripcion' => 'la calles del barrio estan con acumulacion de basura y hay mal olor',
                'fecha' => Carbon::now(),
                'hora' => Carbon::now(),
                'hash' => 'c9f0f895fb98ab9159f51fd0297e236d',
                'latitud' => '-17.773027555677267',
                'longitud' => '-63.18551138108517',
                'tipo_denuncia' => '2',
            ],
            [
                'user_id' => '3',
                'titulo' => 'parque del barrio Buenavista con maleza crecida',
                'descripcion' => 'el barrio tiene su parque con maleza crecida y cubriendo las bancas y los juegos infantiles',
                'fecha' => Carbon::now(),
                'hora' => Carbon::now(),
                'hash' => '45c48cce2e2d7fbdea1afc51c7c6ad26',
                'latitud' => '-17.775975068785108',
                'longitud' => '-63.167728782362964',
                'tipo_denuncia' => '1',
            ],
            [
                'user_id' => '1',
                'titulo' => 'parque del barrio Sendero con maleza crecida',
                'descripcion' => 'el barrio tiene su parque con maleza crecida y se ha vuelto peligroso por las noches debido a esto',
                'fecha' => Carbon::now(),
                'hora' => Carbon::now(),
                'hash' => 'd3d9446802a44259755d38e6d163e820',
                'latitud' => '-17.775570511040563',
                'longitud' => '-63.1597175092185',
                'tipo_denuncia' => '1',
            ],
            [
                'user_id' => '3',
                'titulo' => 'parque del barrio la colmena con maleza crecida',
                'descripcion' => 'el barrio tiene su parque con maleza crecida y se ha vuelto peligroso por las noches debido a esto',
                'fecha' => Carbon::now(),
                'hora' => Carbon::now(),
                'hash' => 'd3d9446802a44259755d38e6d163e342',
                'latitud' => '-17.799827919730454',
                'longitud' => '-63.22939170253412',
                'tipo_denuncia' => '1',
            ],
        ]);
    }
}
